### ISSUE TITLE
Causing build error: "Module not found: Default condition should be last one"

### ISSUE THREAD

**Issue by spalger** [sentienhq/ultralight-s3#11]
When trying to use this library in a next.js project I get a build error with the message "Module not found: Default condition should be last one"

According to https://stackoverflow.com/questions/76127288/module-not-found-error-default-condition-should-be-last-one this is cause by the "default" key in an export map not being the literally last key, which kinda sounds absurd but I'm not too familiar with how export maps work.

https://nodejs.org/api/packages.html indicates that the "default" key "should always come last", but maybe it actually must?

Confirmed that swapping the order of the keys in the package.json file within my node_modules fixes the issue

**Comment by good-lly** [comment]
@spalger good catch! Can you show me your fix/edit from package.json? Or feel free to send PR - I will merge it.

**Comment by spalger** [comment]
Opened https://github.com/sentienhq/ultralight-s3/pull/13
