### ISSUE TITLE
Add browser / Cross-platform capability

### ISSUE THREAD

**Issue by good-lly** [sentienhq/ultralight-s3#2]
Remove, shim/polyfill all dependencies and make script running on everyting

**Comment by Murderlon** [comment]
Hi, I'm one of the maintainers of [Uppy](http://uppy.io), potentially the most used uploader at millions of downloads a year, and I'm considering redoing our `@uppy/aws-s3` plugin as a wrapper of this library as the plugin got out of hand with complexity over the years.

For that to work we would need browser support. What exactly needs to change for that to happen?

**Comment by good-lly** [comment]
@Murderlon good question. So far, I stumbled on some cors issues on fetch - going to give it a shot during a weekend and let you know

**Comment by good-lly** [comment]
@Murderlon ok, after 3 days of downs and downs I was not able to make it work. Either I stumble on an opaque empty 403 Forbidden response or "SignatureDoesNotMatch" XML response ... (pre-signed requests do not make sense for client-side library hence there is no reason to go that path) Maybe, I overlooked something but 
found some issues/excuses regarding similar implementations -> https://github.com/minio/minio-js/issues/729#issuecomment-463538649 

Postponing this issue for now. If you find yourself with some nerves and free time - feel free to send a PR

**Comment by Murderlon** [comment]
Thanks for looking into it! For that's it worth, I would definitely take the route for pre-signed requests. Just accept a url and your own backend or lambda generates the url. Otherwise it's signing on the client which is a lot more complex and potentially less secure.

We support the latter in Uppy: https://uppy.io/docs/aws-s3/#gettemporarysecuritycredentialsoptions
The PR: https://github.com/transloadit/uppy/pull/4519

Would you be open to pre-signed requests?

**Comment by good-lly** [comment]
@Murderlon After reviewing the PR, I think it would be better to create a separate version, fork, or library for this functionality.

The primary motivation here was to provide server/edge S3 features while keeping the library minimal (as the size directly impacts startup/load time at the edge). Additionally, I’ve come across many hacks with presigned requests, so I’d rather keep this simple. Let’s find a way to support both use cases effectively.
